[project]
name = "threadon"
version = "0.1.0"
description = ""
authors = [
    { name="Threadon-Lang", email="threadon-lang@proton.me" }
]
readme = "README.md"
requires-python = ">=3.9"
license = { text = "GPL-2.0" }

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "compiler" }

[tool.setuptools.packages.find]
where = ["compiler"]
exclude = ["docs"]
