[project]
name = "threadon"
version = "0.1.5"
description = ""
authors = [
    { name="Threadon-Lang", email="threadon-lang@proton.me" }
]
readme = "README.md"
requires-python = ">=3.9"
license = { text = "GPL-2.0" }

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "compiler" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["compiler"]

[tool.setuptools.package-data]
threadon = [
    "../stdlib/*.th",
    "../stdlib/**/*.th",
    "../stdlib/**/manifest"
]
